FROM node:lts as runner
WORKDIR /app

ENV NODE_ENV production

COPY next.config.js ./
COPY public ./public
COPY .next ./.next
COPY node_modules ./node_modules
COPY package.json ./package.json

EXPOSE 3000

CMD ["yarn", "start"]